//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamos.Repositorios
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormasPago
    {
        public FormasPago()
        {
            this.Prestamo = new HashSet<Prestamo>();
        }
    
        public int FormaPagoID { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Prestamo> Prestamo { get; set; }
    }
}
