//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamos.Repositorios
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormasPago
    {
        public FormasPago()
        {
            this.Prestamo = new HashSet<Prestamo>();
        }
    
        public int FormaPagoID { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Prestamo> Prestamo { get; set; }
    }
}
