//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamos.Repositorios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrestamosEntities : DbContext
    {
        public PrestamosEntities()
            : base("name=PrestamosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FormasPago> FormasPago { get; set; }
        public DbSet<PrestamoPago> PrestamoPago { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Prestamo> Prestamo { get; set; }
        public DbSet<PagoCuota> PagoCuota { get; set; }
        public DbSet<Pago> Pago { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
