//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamos.Repositorios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int IDPago { get; set; }
        public int PrestamoPagoID { get; set; }
        public decimal ValorPago { get; set; }
        public decimal Saldo { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<int> Cuota { get; set; }
        public Nullable<bool> Pagado { get; set; }
    
        public virtual PrestamoPago PrestamoPago { get; set; }
    }
}
