//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamos.Repositorios
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestamoPago
    {
        public PrestamoPago()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int PrestamoPagoID { get; set; }
        public int NoPrestamo { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
