//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamos.Repositorios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public Prestamo()
        {
            this.PrestamoPago = new HashSet<PrestamoPago>();
        }
    
        public int NoPrestamo { get; set; }
        public int Documento { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public decimal ValorPrestamo { get; set; }
        public int NoCuotas { get; set; }
        public int FormaPagoID { get; set; }
        public decimal Intereses { get; set; }
        public decimal ValorCuota { get; set; }
        public decimal Ganancias { get; set; }
        public decimal Saldo { get; set; }
        public decimal Total { get; set; }
        public bool Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual FormasPago FormasPago { get; set; }
        public virtual ICollection<PrestamoPago> PrestamoPago { get; set; }
    }
}
